apiVersion: v1
kind: PersitentVolumeClaim
metadata: 
  labels: 
    template: postgresql-persistent-template
  name: postgresql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi


